# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemctl < Formula
  desc "CLI tool for Gemini Enterprise management"
  homepage "https://github.com/vb140772/gemctl-go"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.2/gemctl_1.3.2_darwin_amd64.tar.gz"
      sha256 "42d17ffd689be9e3021d672aceddf2ba6bf9a789020980b2b375c308a2b21411"

      def install
        bin.install "gemctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.2/gemctl_1.3.2_darwin_arm64.tar.gz"
      sha256 "e81e6ab406ae3f300bfb708d73d969e2707f8f55719ef2ec1056a11942c92b19"

      def install
        bin.install "gemctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.2/gemctl_1.3.2_linux_amd64.tar.gz"
      sha256 "56e1321fdce050154a7f75efdd8c34a440d511ee8046eb1b0b76cceadf39cfee"
      def install
        bin.install "gemctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.2/gemctl_1.3.2_linux_arm64.tar.gz"
      sha256 "5c726334f576fb2053d5239718235f801d9ad9bc824af73bf0205056cfd9edc7"
      def install
        bin.install "gemctl"
      end
    end
  end
end
