# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gemctl < Formula
  desc "CLI tool for Gemini Enterprise management"
  homepage "https://github.com/vb140772/gemctl-go"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.1/gemctl_1.3.1_darwin_amd64.tar.gz"
      sha256 "8876daca6a4d0225f8731e54d36ef84896ca346ce518fe7d3fc2e99d78b6bf4e"

      def install
        bin.install "gemctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.1/gemctl_1.3.1_darwin_arm64.tar.gz"
      sha256 "fa5f7335586c36cd7a1229ff24bd4980ef4026651246bad048b609e6da6c9f20"

      def install
        bin.install "gemctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.1/gemctl_1.3.1_linux_amd64.tar.gz"
      sha256 "2ac240106147ed813a718f0693a13ab83916b9b306f4aabff7720b3e9044e2a6"
      def install
        bin.install "gemctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vb140772/gemctl-go/releases/download/v1.3.1/gemctl_1.3.1_linux_arm64.tar.gz"
      sha256 "80fd42181015870c9568e9e2a12805087ddbe155a17a2699bef2b0dadefe577c"
      def install
        bin.install "gemctl"
      end
    end
  end
end
